language: java

jdk:
  - oraclejdk9

# Use JDK 8u45. The above line just causes the use of a minor version of Java 8.
    addons:
    apt:
    packages:
    - oracle-java9-installer

script: mvn verify -B
